#!/bin/bash
CDIR=`pwd`
TAG="${TAG:=ram}"
NAMESPACE="${NAMESPACE:=ram-dev}"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
LIGHTGREY='\033[0;33m'
REPO="${REPO:=us-west1-docker.pkg.dev/sonet-cloud/sonetio-dev}"
NC='\033[0m' # No Color
printf "${BLUE}[1] - BUILDING backend with tag ${REPO}:${TAG} - ${NAMESPACE}${NC} \n"


printf "${NC}${BLUE}[2] - DEPLOYING Helm Chart${NC}${LIGHTGREY} \n"
cd /home/ram/src/sonet-k8s-deploy
helm upgrade sonet -n $NAMESPACE helm/sonet-service --reuse-values --set dashboard.imageRepo=$REPO --set dashboard.imageTag=$TAG
if [ $? -eq 0 ]; then
   printf "${NC}${BLUE}[3] - DEPLOYING Helm Chart${NC} -${GREEN}👍 Done${NC}${LIGHTGREY} \n"
else
   say @b@red[[Helm Deployment Failed!]]
   exit
fi
cd $CDIR


printf "${NC}${GREEN}[✅] - Deployment Finished! ${NC} 🥳 \n"
