#!/bin/bash
CDIR=`pwd`
TAG="${TAG:=ram}"
NAMESPACE="${NAMESPACE:=ram-dev}"
REPO="${REPO:=us-west1-docker.pkg.dev/sonet-cloud/sonetio-dev}"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
printf "${BLUE}[1] - REFRESHING chrome broker with ${REPO}:${TAG}${NC} \n"

printf "${BLUE}[2] - DEPLOYING Helm Chart to $NAMESPACE namespace ${NC} \n"
cd /home/ram/src/sonet-k8s-deploy
helm upgrade sonet -n $NAMESPACE helm/sonet-service --reuse-values --set chromeBroker.imageRepo=$REPO --set chromeBroker.imageTag=$TAG --set debug.enabled=true

if [ $? -eq 0 ]; then
   printf "${BLUE}[2] - DEPLOYING Helm Chart${NC} -${GREEN}👍 Done${NC} \n"
else
   say @b@red[[Helm Deployment Failed!]]
   exit
fi
cd $CDIR


printf "${GREEN}[✅] - Refresh Finished! ${NC} 🥳 \n"
