#!/bin/bash
CDIR=`pwd`
TAG="${TAG:=ram}"
NAMESPACE="${NAMESPACE:=ram-dev}"
REPO="${REPO:=us-west1-docker.pkg.dev/sonet-cloud/sonetio-dev}"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color
printf "${BLUE}[1] - BUILDING Docker Image for tag ${TAG}${NC} \n"

if [[ $REPO == "sonetio" ]]; then
        printf "${NC}${RED} - This is a production container registry. Quitting the build ${NC}"
        exit 0
fi

cd /home/ram/src/chrome-broker
docker build . -t $REPO/chrome-broker:$TAG --progress=plain
if [ $? -eq 0 ]; then
	printf "${BLUE}[1] - BUILDING Docker Image${NC} -${GREEN}👍 Done${NC} \n"
else
   say @b@red[[Docker image build Failed]]
   exit 
fi

docker push $REPO/chrome-broker:$TAG
if [ $? -eq 0 ]; then
        printf "${BLUE}[2] - PUSHING Docker Image${NC} -${GREEN}👍 Done${NC} \n"
else
   say @b@red[[Docker image push Failed!]]
   exit
fi

printf "${BLUE}[3] - DEPLOYING Helm Chart to $NAMESPACE namespace ${NC} \n"
cd /home/ram/src/sonet-k8s-deploy
helm upgrade sonet -n $NAMESPACE helm/sonet-service --reuse-values --set chromeBroker.imageRepo=$REPO --set chromeBroker.imageTag=$TAG --set debug.enabled=true

if [ $? -eq 0 ]; then
   printf "${BLUE}[3] - DEPLOYING Helm Chart${NC} -${GREEN}👍 Done${NC} \n"
else
   say @b@red[[Helm Deployment Failed!]]
   exit
fi
cd $CDIR


printf "${GREEN}[✅] - Deployment Finished! ${NC} 🥳 \n"
