#!/bin/bash
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
printf "${GREEN}PRUNING DOCKER!${NC} \n"
printf "${GREEN}"
docker image prune -f
docker system prune -f
printf "${NC}"
echo "👍 - Done!"
