#!/bin/bash
CDIR=`pwd`
TAG="${TAG:=ram}"
NAMESPACE="${NAMESPACE:=ram-dev}"
REPO="${REPO:=us-west1-docker.pkg.dev/sonet-cloud/sonetio-dev}"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
LIGHTGREY='\033[0;33m'
NC='\033[0m' # No Color
printf "${BLUE}[1] - REFRESHING guacamole-clieent with ${REPO}:${TAG}${NC} \n"

printf "${NC}${BLUE}[2] - DEPLOYING Helm Chart${NC}${LIGHTGREY} \n"
cd $SRC/sonet-k8s-deploy
helm upgrade sonet -n $NAMESPACE helm/sonet-service --reuse-values --set webapp.imageRepo=$REPO --set webapp.imageTag=$TAG
if [ $? -eq 0 ]; then
   printf "${NC}${BLUE}[2] - DEPLOYING Helm Chart${NC} -${GREEN}👍 Done${NC}${LIGHTGREY} \n"
else
   say @b@red[[Helm Deployment Failed!]]
   exit
fi
cd $CDIR


printf "${NC}${GREEN}[✅] - REFRESH Finished! ${NC} 🥳 \n"
